import { Email, Location, Phone, WhatsApp } from "../(components)/Svg";

export const contactMethods = [
  {
    icon: <Email className="h-6 w-6" />,
    label: "Email",
    value: "prabhat.dev@gmail.com",
    href: "mailto:prabhat.dev@gmail.com",
    color: "from-purple-500 to-pink-500",
    hoverColor: "hover:text-purple-400",
  },
  {
    icon: <Phone className="h-6 w-6" />,
    label: "Phone",
    value: "+91 9XXXXXXXXX",
    href: "tel:+919XXXXXXXXX",
    color: "from-blue-500 to-cyan-500",
    hoverColor: "hover:text-blue-400",
  },
  {
    icon: <WhatsApp className="w-6 h-6" />,
    label: "WhatsApp",
    value: "+91 9XXXXXXXXX",
    href: "https://wa.me/919XXXXXXXXX",
    color: "from-green-500 to-emerald-500",
    hoverColor: "hover:text-green-400",
  },
  {
    icon: <Location className="h-6 w-6" />,
    label: "Location",
    value: "New Delhi, India 🇮🇳",
    href: null,
    color: "from-orange-500 to-red-500",
    hoverColor: "hover:text-orange-400",
  },
];

// Country codes ki complete list
export const countryCodes = [
  { value: "+1", label: "🇺🇸 United States (+1)" },
  { value: "+44", label: "🇬🇧 United Kingdom (+44)" },
  { value: "+91", label: "🇮🇳 India (+91)" },
  { value: "+86", label: "🇨🇳 China (+86)" },
  { value: "+81", label: "🇯🇵 Japan (+81)" },
  { value: "+49", label: "🇩🇪 Germany (+49)" },
  { value: "+33", label: "🇫🇷 France (+33)" },
  { value: "+61", label: "🇦🇺 Australia (+61)" },
  { value: "+7", label: "🇷🇺 Russia (+7)" },
  { value: "+55", label: "🇧🇷 Brazil (+55)" },
  { value: "+52", label: "🇲🇽 Mexico (+52)" },
  { value: "+34", label: "🇪🇸 Spain (+34)" },
  { value: "+39", label: "🇮🇹 Italy (+39)" },
  { value: "+82", label: "🇰🇷 South Korea (+82)" },
  { value: "+62", label: "🇮🇩 Indonesia (+62)" },
  { value: "+90", label: "🇹🇷 Turkey (+90)" },
  { value: "+31", label: "🇳🇱 Netherlands (+31)" },
  { value: "+46", label: "🇸🇪 Sweden (+46)" },
  { value: "+41", label: "🇨🇭 Switzerland (+41)" },
  { value: "+971", label: "🇦🇪 UAE (+971)" },
  { value: "+966", label: "🇸🇦 Saudi Arabia (+966)" },
  { value: "+65", label: "🇸🇬 Singapore (+65)" },
  { value: "+64", label: "🇳🇿 New Zealand (+64)" },
  { value: "+27", label: "🇿🇦 South Africa (+27)" },
  { value: "+20", label: "🇪🇬 Egypt (+20)" },
];
